apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: smallmanconsultancy.co.uk-tls
spec:
    secretName: smallmanconsultancy.co.uk
    issuerRef:
        Name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: www.smallmanconsultancy.co.uk
    dnsNames:
        - smallmanconsultancy.co.uk
        - www.smallmanconsultancy.co.uk
    acme:
        config:
            - http01:
                    ingressClass: nginx
            domains:
                    - smallmanconsultancy.co.uk
                    - www.smallmanconsultancy.co.uk
